// import './globals.css'
'use client';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import Navbar from '../component/navbar/page';
import '../assets/Bootstrap/dist/css/bootstrap-reboot.css';
import '../assets/Bootstrap/dist/css/bootstrap.css';
import '../assets/Bootstrap/dist/css/bootstrap-grid.css';
import '../assets/css/main.css';
import '../assets/css/dashboard.css';
import '../assets/css/group.css';
import '../assets/css/post.css';
import '../assets/css/profile.css';
import '../assets/css/profileNew.css';
import '../assets/css/messenger.css';
import '../assets/css/newsfeedPost.css';
import '../assets/css/customizeMenu.css';

import Head from 'next/head';
import PreLoader from '@/component/PreLoader';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { useEffect } from 'react';
import { host } from '../../src/environment';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import StoreProvider from '@/redux/provider';
config.autoAddCss = false;
import { Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ['latin'] });
const metadata = {
   title: 'Quantum Possibilities',
   description: 'Generated by create next app',
};

import io from 'socket.io-client';
import { SocketProvider } from './socketProvider/SocketProvider';
export const socket = io(host, { transports: ['websocket'] });

export default function RootLayout({ children }) {
   useEffect(() => {
      const disableTextSelection = (event) => {
         event.preventDefault();
      };

      const disableCopyShortcut = (event) => {
         if (event.ctrlKey && event.key === 'c') {
            event.preventDefault();
         }
      };

      document.body.addEventListener('selectstart', disableTextSelection);
      document.addEventListener('keydown', disableCopyShortcut);
      return () => {
         document.body.removeEventListener('selectstart', disableTextSelection);
         document.removeEventListener('keydown', disableCopyShortcut);
      };
   }, []);

   return (
      <>
         <html lang="en">
            <SocketProvider>
               <StoreProvider>
                  <body className={inter.className}>
                     {children}
                     <Toaster />
                     <ToastContainer />
                     <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
                     <Script src="https://quantumpossibilities.eu:85/assets/js/jQuery/jquery-3.4.1.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/jquery.appear.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/jquery.mousewheel.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/perfect-scrollbar.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/jquery.matchHeight.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/svgxuse.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/imagesloaded.pkgd.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/Headroom.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/velocity.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/ScrollMagic.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/jquery.waypoints.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/jquery.countTo.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/popper.min.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/material.min.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/bootstrap-select.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/smooth-scroll.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/selectize.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/swiper.jquery.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/moment.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/daterangepicker.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/fullcalendar.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/isotope.pkgd.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/ajax-pagination.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/Chart.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/chartjs-plugin-deferred.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/circle-progress.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/loader.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/run-chart.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/jquery.magnific-popup.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/jquery.gifplayer.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/mediaelement-and-player.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/mediaelement-playlist-plugin.min.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/ion.rangeSlider.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/leaflet.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs/MarkerClusterGroup.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/main.js" />
                     <Script src="https://quantumpossibilities.eu:85/assets/js/libs-init/libs-init.js" />
                     {/* <Script defer src="fonts/fontawesome-all.js" /> */}
                     <Script src="https://quantumpossibilities.eu:85/assets/Bootstrap/dist/js/bootstrap.bundle.js" />
                  </body>
               </StoreProvider>
            </SocketProvider>
         </html>
      </>
   );
}

// 
//   <App />
// </SocketProvider>
